# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'AdGridTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdGridTestApp
  pod 'AdGridSDK', :git => 'https://github.com/AdGrid/IOS-Mobile-SDK.git', :tag => '1.1.0'
  # pod 'AdGridSDK', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
  end
end