# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'AdGridTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdGridTestApp
  pod 'AdGridSDK', :git => 'https://github.com/AdGrid/IOS-Mobile-SDK.git', :tag => '1.0.7'

end